[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-image"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version = "2.10.6", features = ["napi4", "compat-mode"]}
napi-derive = "2.9.4"
oxipng = "6.0.0"
mozjpeg-sys = "1.0.0"
libc = "0.2"

[build-dependencies]
napi-build = "2"
