[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-image"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version = "2.3.3", default-features = false, features = ["napi4", "compat-mode"]}
napi-derive = "2"
oxipng = "5.0.0"
mozjpeg-sys = "1.0.0"
libc = "0.2"

[build-dependencies]
napi-build = "1"
