[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-resolver-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.6", features = ["napi4", "serde-json"] }
napi-derive = "2.12.5"
parcel-resolver = { path = "../node-resolver-rs" }
dashmap = "5.4.0"
rayon = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
parcel-dev-dep-resolver = { path = "../dev-dep-resolver" }

[build-dependencies]
napi-build = "2"
