[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-resolver-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.0", features = ["serde-json"] }
napi-derive = "2.12.0"
parcel-resolver = { path = "../node-resolver-rs" }
dashmap = "5.4.0"

[build-dependencies]
napi-build = "2"
