# This workflow builds and releases all packages on the main branch with a canary
# dist tag. These packages contain changes that are not yet available in a publicly
# released version of Atlaspack.
name: Canary Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and release canary
    if: false
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      profile: canary
      release-command: yarn canary:release
      type: canary
