# This workflow builds and releases all packages on the main branch with a canary
# dist tag. These packages contain changes that are not yet available in a publicly
# released version of Parcel.
name: canary-release

on:
  push:
    branches:
      - v2
    paths:
      - yarn.lock
      - verdaccioPublish.js
      - verdaccio.yml
      - rustfmt.toml
      - rust-toolchain
      - README.md
      - package.json
      - lerna.json
      - gulpfile.js
      - Cargo.toml
      - Cargo.lock
      - babel.config.json
      - sciprts/**
      - patches/**
      - packages/**
      - flow-typed/**
      - flow-libs/**
      - docs/**
      - crates/**
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and release canary
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      profile: canary
      release-command: |
        yarn canary:release --summary-file
        node scripts/tag-release.mjs --tag nightly
      type: canary
