# This workflow builds and releases all packages with a dev dist tag. Once published,
# the packages can be installed to streamline the testing and validation of changes, both
# locally and within CI, that have not yet been approved or merged into the main branch.
name: dev-release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and release dev
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      profile: canary
      release-command: yarn dev:release
      type: dev
